### ISSUE TITLE
Error in starting training 

### ISSUE THREAD

**Issue by shakeel-m-s** [pmcgrath249/DeepCVLab#2]
Hi pmcgrath,

I'm Shakeel, a graduate student at UC San Diego. I want to implement 3D Object detection and was looking into the available resources. Thanks for your work and contribution. I tried running your implementation, and I'm running into the following error.

![Annotation 2020-08-05 174440](https://user-images.githubusercontent.com/57313387/89477937-65dd3d00-d743-11ea-94d9-d8a9d7a893b0.png)

IndexError: too many indices for array

I would love to have some clarification regarding this. Any guidance is appreciated! Thank you so much for your time!

**Comment by p-mc-grath** [comment]
Hi, so sorry I did not see the issue.
Could you expand the error message? What steps did you take? Did you adjust the config according to your dataset? Looks like something goes wrong while tensorboard tries to log your hyperparams.
Best

**Comment by p-mc-grath** [comment]
Fixed it. It was a tensor cast when saving the hyper parameters.
